**Pandas** — это библиотека, которая позволяет работать с табличными данными прямо в Python: фильтровать, группировать, соединять таблицы, считать метрики, чистить данные, строить признаки.
    
Главный объект pandas — **DataFrame**. Это таблица *df*.

Столбец таблицы — это **Series**: *df["revenue"]*.

**Pandas** — это основная Python-библиотека для табличной аналитики. Я использую ее, когда нужно быстро исследовать данные, почистить выгрузку, посчитать метрики, сделать группировки, джойны, преобразования и подготовить данные для отчета или визуализации. SQL удобнее для выборки и агрегации в базе, pandas — для дальнейшего анализа в Python.

## Начнем с первой практической задачи.

In [50]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "user_id": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "campaign_id": [101, 101, 101, 102, 102, 102, 103, 103, 103, 103],
    "channel": ["push", "push", "email", "email", "sms", "push", "sms", "email", "push", "sms"],
    "sent": [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    "clicked": [1, 0, 1, 1, 0, 1, 0, 1, 1, 0],
    "purchased": [1, 0, 0, 1, 0, 1, 0, 0, 1, 0],
    "revenue": [1200, 0, 0, 2500, 0, 1800, 0, 0, 900, 0],
    "age": [25, 34, 41, 29, 52, 37, 23, 45, 31, 60],
    "segment": ["mass", "mass", "premium", "premium", "mass", "premium", "mass", "mass", "premium", "mass"]
})

## Задача 1: DataFrame / Series / базовая разведка

Первые 5 строк:

In [2]:
df.head()

,user_id,campaign_id,channel,sent,clicked,purchased,revenue,age,segment
0,1,101,push,1,1,1,1200,25,mass
1,2,101,push,1,0,0,0,34,mass
2,3,101,email,1,1,0,0,41,premium
3,4,102,email,1,1,1,2500,29,premium
4,5,102,sms,1,0,0,0,52,mass

Первые 10 строк:

In [9]:
df.head(10)

,user_id,campaign_id,channel,sent,clicked,purchased,revenue,age,segment
0,1,101,push,1,1,1,1200,25,mass
1,2,101,push,1,0,0,0,34,mass
2,3,101,email,1,1,0,0,41,premium
3,4,102,email,1,1,1,2500,29,premium
4,5,102,sms,1,0,0,0,52,mass
5,6,102,push,1,1,1,1800,37,premium
6,7,103,sms,1,0,0,0,23,mass
7,8,103,email,1,1,0,0,45,mass
8,9,103,push,1,1,1,900,31,premium
9,10,103,sms,1,0,0,0,60,mass

Размер таблицы:

In [3]:
df.shape

(10, 9)

Названия колонок:

In [12]:
df.columns

Index(['user_id', 'campaign_id', 'channel', 'sent', 'clicked', 'purchased',
       'revenue', 'age', 'segment'],
      dtype='str')

Типы колонок:

In [13]:
df.dtypes

user_id        int64
campaign_id    int64
channel          str
sent           int64
clicked        int64
purchased      int64
revenue        int64
age            int64
segment          str
dtype: object

Структура таблицы, non-null, типы:

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   user_id      10 non-null     int64
 1   campaign_id  10 non-null     int64
 2   channel      10 non-null     str
 3   sent         10 non-null     int64
 4   clicked      10 non-null     int64
 5   purchased    10 non-null     int64
 6   revenue      10 non-null     int64
 7   age          10 non-null     int64
 8   segment      10 non-null     str
dtypes: int64(7), str(2)
memory usage: 852.0 bytes

Статистика по числовым колонкам:

In [4]:
df.describe()

,user_id,campaign_id,sent,clicked,purchased,revenue,age
count,10.00000,10.000000,10.0,10.000000,10.000000,10.000000,10.000000
mean,5.50000,102.100000,1.0,0.600000,0.400000,640.000000,37.700000
std,3.02765,0.875595,0.0,0.516398,0.516398,921.592824,11.916841
min,1.00000,101.000000,1.0,0.000000,0.000000,0.000000,23.000000
25%,3.25000,101.250000,1.0,0.000000,0.000000,0.000000,29.500000
50%,5.50000,102.000000,1.0,1.000000,0.000000,0.000000,35.500000
75%,7.75000,103.000000,1.0,1.000000,1.000000,1125.000000,44.000000
max,10.00000,103.000000,1.0,1.000000,1.000000,2500.000000,60.000000

Статистика по категориальным колонкам:

In [16]:
df.describe(include = 'str') ## раньше было df.describe(include = 'object')

       channel segment
count       10      10
unique       3       2
top       push    mass
freq         4       6

Статистика по всем колонкам:

In [17]:
df.describe(include = 'all')

,user_id,campaign_id,channel,sent,clicked,purchased,revenue,age,segment
count,10.00000,10.000000,10,10.0,10.000000,10.000000,10.000000,10.000000,10
unique,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,2
top,NaN,NaN,push,NaN,NaN,NaN,NaN,NaN,mass
freq,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,6
mean,5.50000,102.100000,NaN,1.0,0.600000,0.400000,640.000000,37.700000,NaN
std,3.02765,0.875595,NaN,0.0,0.516398,0.516398,921.592824,11.916841,NaN
min,1.00000,101.000000,NaN,1.0,0.000000,0.000000,0.000000,23.000000,NaN
25%,3.25000,101.250000,NaN,1.0,0.000000,0.000000,0.000000,29.500000,NaN
50%,5.50000,102.000000,NaN,1.0,1.000000,0.000000,0.000000,35.500000,NaN
75%,7.75000,103.000000,NaN,1.0,1.000000,1.000000,1125.000000,44.000000,NaN
max,10.00000,103.000000,NaN,1.0,1.000000,1.000000,2500.000000,60.000000,NaN

Один столбец, Series

In [19]:
df['user_id']

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: user_id, dtype: int64

Несколько столбцов, DataFrame

In [20]:
df[['user_id', 'age']]

   user_id  age
0        1   25
1        2   34
2        3   41
3        4   29
4        5   52
5        6   37
6        7   23
7        8   45
8        9   31
9       10   60

## Задача 2: Фильтрация строк

На том же df сделай:

1. Выведи всех пользователей из сегмента premium.
2. Выведи всех пользователей из канала push.
3. Выведи пользователей, которые кликнули, но не купили.
4. Выведи пользователей из premium, у которых revenue > 0.
5. Выведи пользователей, которые либо из канала sms, либо старше 50 лет.
6. Выведи пользователей, которые не купили.
    
Важно: для нескольких условий используй скобки вокруг каждого условия

In [22]:
df[df['segment'] == 'premium']

,user_id,campaign_id,channel,sent,clicked,purchased,revenue,age,segment
2,3,101,email,1,1,0,0,41,premium
3,4,102,email,1,1,1,2500,29,premium
5,6,102,push,1,1,1,1800,37,premium
8,9,103,push,1,1,1,900,31,premium

In [24]:
df[df['channel'] == 'push']

,user_id,campaign_id,channel,sent,clicked,purchased,revenue,age,segment
0,1,101,push,1,1,1,1200,25,mass
1,2,101,push,1,0,0,0,34,mass
5,6,102,push,1,1,1,1800,37,premium
8,9,103,push,1,1,1,900,31,premium

In [25]:
df[(df['clicked'] == 1) & (df['purchased'] == 0)]

,user_id,campaign_id,channel,sent,clicked,purchased,revenue,age,segment
2,3,101,email,1,1,0,0,41,premium
7,8,103,email,1,1,0,0,45,mass

In [26]:
df[(df['segment'] == 'premium') & (df['revenue'] > 0)]

,user_id,campaign_id,channel,sent,clicked,purchased,revenue,age,segment
3,4,102,email,1,1,1,2500,29,premium
5,6,102,push,1,1,1,1800,37,premium
8,9,103,push,1,1,1,900,31,premium

In [27]:
df[(df['channel'] == 'sms') | (df['age'] > 50)]

,user_id,campaign_id,channel,sent,clicked,purchased,revenue,age,segment
4,5,102,sms,1,0,0,0,52,mass
6,7,103,sms,1,0,0,0,23,mass
9,10,103,sms,1,0,0,0,60,mass

In [28]:
df[df['purchased'] == 0]

,user_id,campaign_id,channel,sent,clicked,purchased,revenue,age,segment
1,2,101,push,1,0,0,0,34,mass
2,3,101,email,1,1,0,0,41,premium
4,5,102,sms,1,0,0,0,52,mass
6,7,103,sms,1,0,0,0,23,mass
7,8,103,email,1,1,0,0,45,mass
9,10,103,sms,1,0,0,0,60,mass

## Задача 3: Создание новых колонок

На этом же df создай новые колонки:
    
1. revenue_per_click = revenue / clicked, но если clicked = 0, должно быть 0, а не бесконечность/ошибка.
2. is_buyer = 1, если purchased = 1, иначе 0.
3. age_group:
   - если age < 30 → "young"
   - если age < 50 → "middle"
   - иначе → "senior"
4. client_value:
   - если revenue >= 2000 → "high"
   - если revenue > 0 → "medium"
   - если revenue = 0 → "zero"

In [51]:
df['revenue_per_click'] = np.where(
    df['clicked'] == 0,
    0,
    df['revenue'] / df['clicked']
)

In [52]:
df

,user_id,campaign_id,channel,sent,clicked,purchased,revenue,age,segment,revenue_per_click
0,1,101,push,1,1,1,1200,25,mass,1200.0
1,2,101,push,1,0,0,0,34,mass,0.0
2,3,101,email,1,1,0,0,41,premium,0.0
3,4,102,email,1,1,1,2500,29,premium,2500.0
4,5,102,sms,1,0,0,0,52,mass,0.0
5,6,102,push,1,1,1,1800,37,premium,1800.0
6,7,103,sms,1,0,0,0,23,mass,0.0
7,8,103,email,1,1,0,0,45,mass,0.0
8,9,103,push,1,1,1,900,31,premium,900.0
9,10,103,sms,1,0,0,0,60,mass,0.0

In [37]:
df['is_buyer'] = df['purchased']

In [38]:
df

,user_id,campaign_id,channel,sent,clicked,purchased,revenue,age,segment,revenue_per_click,is_buyer
0,1,101,push,1,1,1,1200,25,mass,1200.0,1
1,2,101,push,1,0,0,0,34,mass,0.0,0
2,3,101,email,1,1,0,0,41,premium,0.0,0
3,4,102,email,1,1,1,2500,29,premium,2500.0,1
4,5,102,sms,1,0,0,0,52,mass,0.0,0
5,6,102,push,1,1,1,1800,37,premium,1800.0,1
6,7,103,sms,1,0,0,0,23,mass,0.0,0
7,8,103,email,1,1,0,0,45,mass,0.0,0
8,9,103,push,1,1,1,900,31,premium,900.0,1
9,10,103,sms,1,0,0,0,60,mass,0.0,0

In [53]:
df['age_group'] = np.where(
    df['age'] < 30,
    'young',
    np.where(
        df['age'] >= 50,
        'senior',
        'middle'
    )
)

In [54]:
df

,user_id,campaign_id,channel,sent,clicked,purchased,revenue,age,segment,revenue_per_click,age_group
0,1,101,push,1,1,1,1200,25,mass,1200.0,young
1,2,101,push,1,0,0,0,34,mass,0.0,middle
2,3,101,email,1,1,0,0,41,premium,0.0,middle
3,4,102,email,1,1,1,2500,29,premium,2500.0,young
4,5,102,sms,1,0,0,0,52,mass,0.0,senior
5,6,102,push,1,1,1,1800,37,premium,1800.0,middle
6,7,103,sms,1,0,0,0,23,mass,0.0,young
7,8,103,email,1,1,0,0,45,mass,0.0,middle
8,9,103,push,1,1,1,900,31,premium,900.0,middle
9,10,103,sms,1,0,0,0,60,mass,0.0,senior

In [55]:
conditions = [
    df['revenue'] >= 2000,
    df['revenue'] == 0
]

choices = [
    "high",
    "zero"
]

df["client_value"] = np.select(
    conditions,
    choices, 
    default = 'medium'
)

In [56]:
df

,user_id,campaign_id,channel,sent,clicked,purchased,revenue,age,segment,revenue_per_click,age_group,client_value
0,1,101,push,1,1,1,1200,25,mass,1200.0,young,medium
1,2,101,push,1,0,0,0,34,mass,0.0,middle,zero
2,3,101,email,1,1,0,0,41,premium,0.0,middle,zero
3,4,102,email,1,1,1,2500,29,premium,2500.0,young,high
4,5,102,sms,1,0,0,0,52,mass,0.0,senior,zero
5,6,102,push,1,1,1,1800,37,premium,1800.0,middle,medium
6,7,103,sms,1,0,0,0,23,mass,0.0,young,zero
7,8,103,email,1,1,0,0,45,mass,0.0,middle,zero
8,9,103,push,1,1,1,900,31,premium,900.0,middle,medium
9,10,103,sms,1,0,0,0,60,mass,0.0,senior,zero

## Задача 4: Пропуски

In [57]:
df_missing = df.copy()

df_missing.loc[1, "revenue"] = np.nan
df_missing.loc[4, "channel"] = np.nan
df_missing.loc[7, "age"] = np.nan
df_missing.loc[9, "segment"] = np.nan

In [58]:
df_missing

,user_id,campaign_id,channel,sent,clicked,purchased,revenue,age,segment,revenue_per_click,age_group,client_value
0,1,101,push,1,1,1,1200.0,25.0,mass,1200.0,young,medium
1,2,101,push,1,0,0,NaN,34.0,mass,0.0,middle,zero
2,3,101,email,1,1,0,0.0,41.0,premium,0.0,middle,zero
3,4,102,email,1,1,1,2500.0,29.0,premium,2500.0,young,high
4,5,102,NaN,1,0,0,0.0,52.0,mass,0.0,senior,zero
5,6,102,push,1,1,1,1800.0,37.0,premium,1800.0,middle,medium
6,7,103,sms,1,0,0,0.0,23.0,mass,0.0,young,zero
7,8,103,email,1,1,0,0.0,NaN,mass,0.0,middle,zero
8,9,103,push,1,1,1,900.0,31.0,premium,900.0,middle,medium
9,10,103,sms,1,0,0,0.0,60.0,NaN,0.0,senior,zero

Сделай:

1. Посмотри, сколько пропусков в каждой колонке.
2. Выведи строки, где revenue пропущен.
3. Выведи строки, где channel не пропущен.
4. Замени пропуски в revenue на 0.
5. Замени пропуски в channel на "unknown".
6. Удали строки, где пропущен age.
7. Удали строки, где пропущен segment.

In [61]:
df_missing.isna().sum()

user_id              0
campaign_id          0
channel              1
sent                 0
clicked              0
purchased            0
revenue              1
age                  1
segment              1
revenue_per_click    0
age_group            0
client_value         0
dtype: int64

In [65]:
df_missing[df_missing['revenue'].isna()]

,user_id,campaign_id,channel,sent,clicked,purchased,revenue,age,segment,revenue_per_click,age_group,client_value
1,2,101,push,1,0,0,NaN,34.0,mass,0.0,middle,zero

In [69]:
df_missing[df_missing['channel'].notna()]

,user_id,campaign_id,channel,sent,clicked,purchased,revenue,age,segment,revenue_per_click,age_group,client_value
0,1,101,push,1,1,1,1200.0,25.0,mass,1200.0,young,medium
1,2,101,push,1,0,0,NaN,34.0,mass,0.0,middle,zero
2,3,101,email,1,1,0,0.0,41.0,premium,0.0,middle,zero
3,4,102,email,1,1,1,2500.0,29.0,premium,2500.0,young,high
5,6,102,push,1,1,1,1800.0,37.0,premium,1800.0,middle,medium
6,7,103,sms,1,0,0,0.0,23.0,mass,0.0,young,zero
7,8,103,email,1,1,0,0.0,NaN,mass,0.0,middle,zero
8,9,103,push,1,1,1,900.0,31.0,premium,900.0,middle,medium
9,10,103,sms,1,0,0,0.0,60.0,NaN,0.0,senior,zero

In [73]:
df_missing.loc[df_missing["revenue"].isna(), "revenue"] = 0

In [74]:
df_missing

,user_id,campaign_id,channel,sent,clicked,purchased,revenue,age,segment,revenue_per_click,age_group,client_value
0,1,101,push,1,1,1,1200.0,25.0,mass,1200.0,young,medium
1,0,0,push,1,0,0,0.0,34.0,mass,0.0,middle,zero
2,3,101,email,1,1,0,0.0,41.0,premium,0.0,middle,zero
3,4,102,email,1,1,1,2500.0,29.0,premium,2500.0,young,high
4,5,102,NaN,1,0,0,0.0,52.0,mass,0.0,senior,zero
5,6,102,push,1,1,1,1800.0,37.0,premium,1800.0,middle,medium
6,7,103,sms,1,0,0,0.0,23.0,mass,0.0,young,zero
7,8,103,email,1,1,0,0.0,NaN,mass,0.0,middle,zero
8,9,103,push,1,1,1,900.0,31.0,premium,900.0,middle,medium
9,10,103,sms,1,0,0,0.0,60.0,NaN,0.0,senior,zero

In [76]:
df_missing.loc[df_missing["channel"].isna(), "channel"] = 'unknown'

In [77]:
df_missing

,user_id,campaign_id,channel,sent,clicked,purchased,revenue,age,segment,revenue_per_click,age_group,client_value
0,1,101,push,1,1,1,1200.0,25.0,mass,1200.0,young,medium
1,0,0,push,1,0,0,0.0,34.0,mass,0.0,middle,zero
2,3,101,email,1,1,0,0.0,41.0,premium,0.0,middle,zero
3,4,102,email,1,1,1,2500.0,29.0,premium,2500.0,young,high
4,5,102,unknown,1,0,0,0.0,52.0,mass,0.0,senior,zero
5,6,102,push,1,1,1,1800.0,37.0,premium,1800.0,middle,medium
6,7,103,sms,1,0,0,0.0,23.0,mass,0.0,young,zero
7,8,103,email,1,1,0,0.0,NaN,mass,0.0,middle,zero
8,9,103,push,1,1,1,900.0,31.0,premium,900.0,middle,medium
9,10,103,sms,1,0,0,0.0,60.0,NaN,0.0,senior,zero

In [82]:
df_missing = df_missing.dropna(subset=["age"])

In [83]:
df_missing = df_missing.dropna(subset=["segment"])

In [84]:
df_missing

,user_id,campaign_id,channel,sent,clicked,purchased,revenue,age,segment,revenue_per_click,age_group,client_value
0,1,101,push,1,1,1,1200.0,25.0,mass,1200.0,young,medium
1,0,0,push,1,0,0,0.0,34.0,mass,0.0,middle,zero
2,3,101,email,1,1,0,0.0,41.0,premium,0.0,middle,zero
3,4,102,email,1,1,1,2500.0,29.0,premium,2500.0,young,high
4,5,102,unknown,1,0,0,0.0,52.0,mass,0.0,senior,zero
5,6,102,push,1,1,1,1800.0,37.0,premium,1800.0,middle,medium
6,7,103,sms,1,0,0,0.0,23.0,mass,0.0,young,zero
8,9,103,push,1,1,1,900.0,31.0,premium,900.0,middle,medium